### ISSUE TITLE
Another bbcode-mode already exists

### ISSUE THREAD

**Issue by fehmud** [ejmr/bbcode-mode#1]
Hi,

another older bbcode-mode already exists.  This could cause conflicts. Here it is:

https://bitbucket.org/jfm/emacs-bbcode/

**Comment by ejmr** [comment]
Thanks for bringing that to my attention.  But come on, what self-respecting programmer doesn't enjoy reinventing the wheel sometimes?

**Comment by fehmud** [comment]
Hahaha! Right ;-)

I told you because name conflicts are annoying.  Actually, last time I checked, all packages for editing BBCode were very basic, so much that I thought about writing my own, but at the time my knowledge of Emacs Lisp was even less than it is now, and know I don't need a BBCode mode anymore.  I stumbled upon yours by chance.  

So your package is a welcome contribution, thanks for sharing.

Have a nice day.

**Comment by lassik** [comment]
@egarrulo Thanks for bringing this to our attention. I went through the code (https://bitbucket.org/jfm/emacs-bbcode/src). It's very bare-bones and doesn't seem to have any features that this one by @ejmr doesn't have. Indeed they are very similar.

EmacsWiki (https://www.emacswiki.org/emacs/BbCode) also lists a third mode, `xbbcode-mode` by Xah Lee, but very unusually for an Emacs mode it's behind a paywall and he's asking $3 for it.

This mode by @ejmr seems to be the only one installable via MELPA, which is pretty much a requirement for me these days, so personally I will be contributing to this one.
