### ISSUE TITLE
Keybindings fail with `void-function` error

### ISSUE THREAD

**Issue by swsnr** [ejmr/bbcode-mode#4]
Using GNU Emacs 24.2.93.1 (latest pretest from http://emacsformacosx.com) keybindings to insert tags fail with `void-function` error.

However, invoking the corresponding function manually with `M-x` still works.

STR:
1. `C-x C-f test.bbcode`
2. `C-c C-t b`
3. See the error `Symbol's function definition is void: bbcode/insert-tag-b` appear in the minibuffer.

However, `M-x bbcode/insert-tag-b` inserts `[b][/b]` tag as expected.

**Comment by swsnr** [comment]
PS:  `bbcode-mode` is installed from MELPA, and no additional configuration is done, i.e. `bbcode-mode.el` is autoloaded when visiting a BBCode file.

Interestingly, visiting `bbcode-mode.el` and eval'ing it with `eval-buffer` fixes this issue.

**Comment by swsnr** [comment]
This issue is apparently caused by using uninterned symbols for tag commands.  Replacing `make-symbol` with `intern` in [line 133](https://github.com/ejmr/bbcode-mode/blob/8e47ffd5b2af415552782d7e7c1fc3f92796687f/bbcode-mode.el#L133) fixes this issue.

**Comment by ejmr** [comment]
Thank you for both the useful bug report and the patch to fix it.  I needed to fix an error related to `void-function` on another project, and then coincidentally you sent this, which was also the solution to my other error.  So double-thanks!

I added your name to the README as a contributor.  By default I link to people's GitHub pages, but if you would rather it links to somewhere else please let me know.

**Comment by swsnr** [comment]
You're welcome :-) I am glad that I could help you.
